default_stages: [commit]
default_language_version:
  python: python3.9
repos:
  - repo: local
    hooks:
      - id: test
        name: test
        entry: python test.py
        language: python
        pass_filenames: false
        always_run: true