default_stages: [commit]
default_language_version:
  python: python3.9
repos:
  - repo: local
    hooks:
      - id: test
        name: test
        entry: python Assignment3&4/test.py -v
        language: python
        additional_dependencies: [requests, numpy, flask, nltk, scikit_learn]
        pass_filenames: false
        always_run: true